### ISSUE TITLE
need `GET` user Info API

### ISSUE THREAD

**Issue by Yuankai619** [NTOU-Order-Now/Order-Now-Backend#80]
Request Header:
Authorization: Bearer <your-jwt-token>

Response Body:
{
  "status": 200,
  "message": "Success",
  "data": {
    "id": userId,
    "username": username,
    "email": userEmail,
    "avatarUrl": url,
    "Role": role,
}

**Comment by owen0806** [comment]
Response Body will return storeId if user role is _MERCHANT_
